docker: set new gentoo skel base image to jenkins

diff --git a/charts/jenkins/docker/jenkins/skel/Dockerfile b/charts/jenkins/docker/jenkins/skel/Dockerfile
--- a/charts/jenkins/docker/jenkins/skel/Dockerfile
+++ b/charts/jenkins/docker/jenkins/skel/Dockerfile
@@ -1,15 +1,22 @@
 # Gentoo Jenkins Container
+## Include the portage tree
+FROM gentoo/portage:latest as portage
 
+## Use the gentoo skel as base image
+# To build tuner/gentoo-jenkins:latest run
+#     ./manage_docker.sh jenkins
 FROM tuner/gentoo-jenkins:latest
-RUN eix-sync && \
-    emerge -D portage && \
-    (emerge -D --autounmask-write dev-java/openjdk-bin || true) && \
-    etc-update --automode -5 && \
-    emerge -D dev-java/openjdk-bin && \
-    (emerge -D --autounmask-write dev-util/jenkins-bin || true) && \
+
+## Copy the portage tree
+COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo
+
+## Install Jenkins
+#FROM tuner/gentoo-jenkins:latest
+RUN (emerge -D --autounmask-write dev-util/jenkins-bin || true) && \
     etc-update --automode -5 && \
     emerge -D dev-util/jenkins-bin && \
     emerge -D app-misc/jq
-RUN rm /var/cache/eix/* && \
-    rm -rf /usr/portage/* 
 
+## Do cleanup
+RUN rm -rf /var/db/repos/gentoo && \
+    rm -rf /var/cache/distfiles/*
